set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default:
    @just --list

configure:
    cmake -S ../.. -B build -DCMAKE_BUILD_TYPE=Debug

build: configure
    cmake --build build --target minimal_example

run *ARGS: build
    ./build/examples/minimal/minimal_example {{ARGS}}

help: build
    ./build/examples/minimal/minimal_example -h
